name: flutter_card_game_models
description: A starting point for Dart libraries or applications.
version: 1.1.0
repository: https://github.com/Mylab6/OpenSourceCardGameModels

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
